lora-aprs/LoRa_APRS_iGate

.github/workflows/main.yml
src/configuration.cpp
src/configuration.h

improve config management to use default values. the version number should be removed from the json config.

Improve config management

---

platformio.ini

update ftp server version to 0.9.4

update ftp server version

---

src/TaskRouter.cpp

stupid logical mistake

---

src/TaskEth.cpp
src/TaskWifi.cpp
src/project_configuration.cpp
src/project_configuration.h

[WIP] Static IP für W-Lan / ETH

---

data/is-cfg.json

update config template for #84

add config template for fixed address

---

README.md
lib/LoRa_APRS/LoRa_APRS.cpp
lib/System/TaskManager.cpp
lib/System/Timer.cpp
platformio.ini
src/LoRa_APRS_iGate.cpp
src/Task.h
src/TaskModem.cpp

- static IP for Wifi and Ethernet (#84)
-  Digi fix (#99)

Version 21.35.0

---

data/is-cfg.json
lib/LoRa_APRS/LoRa_APRS.cpp
lib/LoRa_APRS/LoRa_APRS.h
src/TaskModem.cpp
src/project_configuration.cpp
src/project_configuration.h

Reverts lora-aprs/LoRa_APRS_iGate#106
#114 reported an issue - will revert now and add later again

Revert "Digipeater - Different LoRa Settings for RX and TX"

---

data/is-cfg.json
lib/APRS-IS/APRS-IS.cpp
lib/APRS-IS/APRS-IS.h
lib/BoardFinder/BoardFinder.cpp
lib/BoardFinder/BoardFinder.h
lib/ConfigurationManagement/configuration.cpp
lib/ConfigurationManagement/configuration.h
lib/System/System.cpp
lib/System/System.h
lib/System/TaskManager.cpp
platformio.ini
scripts/check_version.py
src/LoRa_APRS_iGate.cpp
src/TaskAprsIs.cpp
src/TaskAprsIs.h
src/TaskEth.cpp
src/TaskEth.h
src/TaskFTP.cpp
src/TaskMQTT.cpp
src/TaskMQTT.h
src/TaskModem.cpp
src/TaskNTP.cpp
src/TaskOTA.cpp
src/TaskRouter.cpp
src/TaskWifi.cpp
src/project_configuration.cpp
src/project_configuration.h

update logger lib and add syslog support

Logger update

---

lib/BoardFinder/BoardFinder.cpp
lib/BoardFinder/BoardFinder.h
platformio.ini
src/TaskBeacon.cpp
src/TaskBeacon.h

This is very convenient for debug.

Push button to send beacon immediately.

---

lib/LoRa/LoRa.cpp
lib/LoRa/LoRa.h
src/LoRa_APRS_iGate.cpp
src/TaskModem.cpp

This PR avoids the collision.
This code also pull-requested at https://github.com/sandeepmistry/arduino-LoRa/pull/574

Collision avoidance

---

platformio.ini
src/LoRa_APRS_iGate.cpp
src/Task.h
src/TaskRadiolib.cpp
src/TaskRadiolib.h

Due to no update since Feb. 2021 on https://github.com/sandeepmistry/arduino-LoRa,
I had tried to use https://github.com/jgromes/RadioLib and work fine in my environment.
I don't know which is better implementation.
If you like, please merge this.

Add TaskRadiolib.

---

lib/ConfigurationManagement/configuration.cpp

comment write on read

---

lib/NTPClient/NTPClient.h
src/TaskOTA.cpp

ntp sync ota upload

---

src/TaskRadiolib.cpp

Can be seen when an "unknown packet" comes in.

Fix for incorrect formatting string

---

data/is-cfg.json
platformio.ini
src/LoRa_APRS_iGate.cpp
src/TaskOTA.cpp
src/TaskRadiolib.cpp

Hi,
I would like to suggest several small changes to the firmware:
1. Disable syslog by default. It seems weird to me that the logs are sent to an unkown server. You should let the user enable that for them if they want (I do not even know how this works ?)
2. Add a watchdog timer in case the device hangs unexpectedly (Also addresses a current issue, #95 ).
3. Fix the monitor flag in the plaformio.ini (otherwise the terminal will not display colored text)
4. An extra "%s" was left in a log line (TaskRadiolib).

Several fixes and watchdog

---

src/LoRa_APRS_iGate.cpp
src/TaskEth.cpp

fix eth issue

---

platformio.ini

Bump RadioLib from 5.6.0 to 5.7.0

Bump RadioLib from 5.6.0 to 5.7.0

---

platformio.ini

Bump espressif32 from 6.0.1 to 6.1.0

Bump espressif32 from 6.0.1 to 6.1.0

---

platformio.ini

Bump ArduinoJson from 6.20.1 to 6.21.0

Bump ArduinoJson from 6.20.1 to 6.21.0

---

platformio.ini

Bump ArduinoJson from 6.21.0 to 6.21.2

Bump ArduinoJson from 6.21.0 to 6.21.2

---

data/is-cfg.json
src/LoRa_APRS_iGate.cpp
src/TaskAprsIs.cpp
src/TaskAprsIs.h
src/TaskRadiolib.cpp
src/project_configuration.cpp
src/project_configuration.h

Send aprs-is messages on HF if activated

---

src/TaskRadiolib.cpp

Fix access to queue

---

src/TaskRadiolib.cpp

fix TX issue

---

platformio.ini

Bump ESP-FTP-Server-Lib from 0.11.0 to 0.13.0

Bump ESP-FTP-Server-Lib from 0.11.0 to 0.13.0

---

platformio.ini

Bump espressif32 from 6.3.1 to 6.3.2

Bump espressif32 from 6.3.1 to 6.3.2

---

platformio.ini

Bump ESP-FTP-Server-Lib from 0.13.0 to 0.14.0

Bump ESP-FTP-Server-Lib from 0.13.0 to 0.14.0

---

platformio.ini

Bump ArduinoJson from 6.21.2 to 6.21.3

Bump ArduinoJson from 6.21.2 to 6.21.3

---

platformio.ini

Bump RadioLib from 6.0.0 to 6.1.0

Bump RadioLib from 6.0.0 to 6.1.0

---

platformio.ini

Bump ArduinoJson from 6.21.3 to 6.21.4

Bump ArduinoJson from 6.21.3 to 6.21.4

---

platformio.ini

Bump RadioLib from 6.1.0 to 6.3.0

Bump RadioLib from 6.1.0 to 6.3.0

---

platformio.ini

Bump TinyGPSPlus from 1.0.3 to 1.1.0

Bump TinyGPSPlus from 1.0.3 to 1.1.0

---

platformio.ini

Bump RadioLib from 6.3.0 to 6.5.0

Bump RadioLib from 6.3.0 to 6.5.0

---

platformio.ini

Bump ArduinoJson from 6.21.4 to 7.0.4

Bump ArduinoJson from 6.21.4 to 7.0.4

---

platformio.ini

Bump RadioLib from 6.5.0 to 6.6.0

Bump RadioLib from 6.5.0 to 6.6.0

---

src/ConfigurationManagement/configuration.cpp
src/ConfigurationManagement/configuration.h
src/TaskMQTT.cpp
src/project_configuration.cpp
src/project_configuration.h

Bugfix/dynamic json document deprecated in arduino json #356

---

platformio.ini

Bump ArduinoJson from 7.0.4 to 7.1.0

Bump ArduinoJson from 7.0.4 to 7.1.0
